
var apple = -5;
console.log("First Number:", apple);
var children = 2;
console.log("Second Number:", children);
var favNumber = 1.4;
console.log("Third Number:", favNumber);
var anniversary = 91810;
console.log("Forth Number:", anniversary);
var myName = "Leila Chung";
console.log("First String:", myName);
var message = "Study, Study, Study!";
console.log("Second String:", message);
var truck = "Ford F250 Diesel";
console.log("Third String:", truck);
var riceIsLife = true;
console.log("First Boolean:", riceIsLife);
var codingIsFun = true;
console.log("Second Boolean:", codingIsFun);
var firstBorn;
console.log("Undefined Variable:", firstBorn);
